name: test_eco
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  http: ^1.1.0
  url_launcher: ^6.2.0
  hive: ^2.2.3
  bluetooth_print: ^4.3.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  path_provider: ^2.1.1
  shimmer: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Regular
      fonts:  
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf